inherit_from: .rubocop_todo.yml

require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/*/**

Metrics/BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - script/**/*
    - vendor/**/*
