language: ruby
rvm:
  - 2.5
before_install: gem install bundler -v 1.11.2
cache: bundler
script: script/cibuild
env:
  matrix:
    - JEKYLL_VERSION="~> 3.0"
    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
