language: ruby
rvm:
  - &ruby 2.4
cache: bundler
script: script/cibuild
env:
  matrix:
    - JEKYLL_VERSION="~> 3.0"
    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
matrix:
  include:
    - rvm: *ruby
      name: "Profile Memory Usage"
      script: bundle exec ruby script/memprof
